name: Wait for CI

on:
  workflow_run:
    workflows: 
      - CI
      - 'CI dispatch'
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  WORKFLOWS_IDS: ci.yml, dispatch.yml
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  wait:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.await-action.outputs.wait-result }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell 
      - name: Awaits
        run: |
          echo Hooray,
          echo I waited.
          
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Awaits
        id: await-action
        uses: ./.github/actions/wait
        with:
          branch: ${{ github.event.workflow_run.head_sha }}
          sha: ${{ github.event.workflow_run.head_branch }}
          workflowsIds: ${{ env.WORKFLOWS_IDS }}

      - name: Get result
        run: echo "${{ steps.await-action.outputs.wait-result }}"
        env:
          outcome: lala
          
  deploy:
    name: Deploys something
    runs-on: ubuntu-latest
    needs:
      - wait
    steps:
      - uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: print output
      - run: echo ${{needs.job1.outputs.output1}}
  deploy-else:
    name: Deploys something else
    runs-on: ubuntu-latest
    needs:
      - wait
    steps:
      - uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
